apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv
  labels:
    app: sonarqube
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/sonarqube-data
